# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestAutolayout' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'AFNetworking'
  pod 'JSONModel'
end

target 'TestTodayExtension' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'JSONModel'
    pod 'SDWebImage'
end

target 'TestNotificationContent' do
    pod 'SDWebImage'
end
